const dataPerformanceSummaryData = [
    {
      testCase: "5G Auto Data Test Drive",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "9.78", udpTputREF: "9.80",
      udpJitterDUT: "1.99", udpJitterREF: "1.91",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "3.96", udpPacketLossREF: "2.35",
      pingDUT: "115.56", pingREF: "148.09",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "#99FA99", 
        udpTputREF: "#99FA99",
        udpJitterDUT: "#99FA99", 
        udpJitterREF: "#99FA99",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "#99FA99", 
        udpPacketLossREF: "#99FA99",
        pingDUT: "#FF00FF", 
        pingREF: "#FF00FF",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""
      }
    },
    {
      testCase: "5G Auto Data Test Stationary Location 1 DL",
      httpSsTputDUT: "100.33", httpSsTputREF: "111.51",
      httpMsTputDUT: "264.96", httpMsTputREF: "283.19",
      udpTputDUT: "185.80", udpTputREF: "185.01",
      udpJitterDUT: "0.07", udpJitterREF: "0.07",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "8.33", udpPacketLossREF: "8.21",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "#FFFF00", 
        httpSsTputREF: "#FFFF00",
        httpMsTputDUT: "#99FA99", 
        httpMsTputREF: "#99FA99",
        udpTputDUT: "#99FA99", 
        udpTputREF: "#99FA99",
        udpJitterDUT: "#99FA99", 
        udpJitterREF: "#99FA99",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "#99FA99", 
        udpPacketLossREF: "#99FA99",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""
      }
    },
    {
      testCase: "5G Auto Data Test Stationary Location 1 UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""
      }
    },
    {
      testCase: "5G Auto Data Test Stationary Location 2 DL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test Stationary Location 2 UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test Stationary Location 3 DL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test Stationary Location 3 UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Play-store app DL Stationary",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Web-Kepler",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test MHS Drive",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test MHS Stationary Location 1 DL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test MHS Stationary Location 1 UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test MHS Stationary Location 2 DL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G Auto Data Test MHS Stationary Location 2 UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G NSA Data Test Drive",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G NSA Data Test Stationary Moderate RF DL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""}
    },
    {
      testCase: "5G NSA Data Test Stationary Moderate RF UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""
      }
    },
    {
      testCase: "5G NSA Data Test Stationary Poor RF DL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""
      }
    },
    {
      testCase: "5G NSA Data Test Stationary Poor RF UL",
      httpSsTputDUT: "N/A", httpSsTputREF: "N/A",
      httpMsTputDUT: "N/A", httpMsTputREF: "N/A",
      udpTputDUT: "N/A", udpTputREF: "N/A",
      udpJitterDUT: "N/A", udpJitterREF: "N/A",
      udpLatencyDUT: "N/A", udpLatencyREF: "N/A",
      udpPacketLossDUT: "N/A", udpPacketLossREF: "N/A",
      pingDUT: "N/A", pingREF: "N/A",
      webpageLoadTimeDUT: "N/A", webpageLoadTimeREF: "N/A",
      passFailLinks: "N/A",
      cellColors: {
        httpSsTputDUT: "", 
        httpMsTputREF: "", 
        httpSsTputDUT: "", 
        httpSsTputREF: "",
        httpMsTputDUT: "", 
        httpMsTputREF: "",
        udpTputDUT: "", 
        udpTputREF: "",
        udpJitterDUT: "", 
        udpJitterREF: "",
        udpLatencyDUT: "", 
        udpLatencyREF: "",
        udpPacketLossDUT: "", 
        udpPacketLossREF: "",
        pingDUT: "", 
        pingREF: "",
        webpageLoadTimeDUT: "", 
        webpageLoadTimeREF: ""
      }
    },
];

export default dataPerformanceSummaryData;
